ECR_LABEL_MAP = {
    'afraid': 'negative',
    'angry': 'negative',
    'annoyed': 'negative',
    'anticipating': 'curious',
    'anxious': 'negative',
    'apprehensive': 'negative',
    'ashamed': 'negative',
    'caring': 'like',
    'confident': 'like',
    'content': 'like',
    'devastated': 'negative',
    'disappointed': 'negative',
    'disgusted': 'negative',
    'embarrassed': 'negative',
    'excited': 'happy',
    'faithful': 'like',
    'furious': 'negative',
    'grateful': 'grateful',
    'guilty': 'negative',
    'hopeful': 'like',
    'impressed': 'like',
    'jealous': 'negative',
    'joyful': 'happy',
    'lonely': 'negative',
    'nostalgic': 'nostalgia',
    'prepared': 'like',
    'proud': 'like',
    'sad': 'negative',
    'sentimental': 'nostalgia',
    'surprised': 'surprise',
    'terrified': 'negative',
    'trusting': 'agreement',
}
ECR_LABELS = ['like', 'negative', 'curious', 'grateful', 'neutral', 'happy', 'surprise', 'nostalgia', 'agreement']